/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_hadoop_yarn_server_nodemanager_containermanager_launcher_GPUMonitor */

#ifndef _Included_org_apache_hadoop_yarn_server_nodemanager_containermanager_launcher_GPUMonitor
#define _Included_org_apache_hadoop_yarn_server_nodemanager_containermanager_launcher_GPUMonitor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_hadoop_yarn_server_nodemanager_containermanager_launcher_GPUMonitor
 * Method:    initnvml
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_apache_hadoop_yarn_server_nodemanager_containermanager_launcher_GPUMonitor_initnvml
  (JNIEnv *, jobject);

/*
 * Class:     org_apache_hadoop_yarn_server_nodemanager_containermanager_launcher_GPUMonitor
 * Method:    getState
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_apache_hadoop_yarn_server_nodemanager_containermanager_launcher_GPUMonitor_getState
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
